### ISSUE TITLE
Bug with kgsGtp

### ISSUE THREAD

**Issue by Cabu** [gcp/leela-zero#1146]
Displaying ponder information at the end of the search break kgsGtp with an EOF.

```  R4 ->      31 (V: 47.50%) (N: 10.79%) PV: R4 D16 C17 D17 C16 C15 B15 B14 C14
 C16 ->      31 (V: 47.16%) (N: 11.42%) PV: C16 Q4 R3 R4 Q3 P3 P2 O2
 D17 ->      30 (V: 47.28%) (N: 10.87%) PV: D17 Q4 R3 R4 Q3 P3 P2 O2 O3 P4
  Q4 ->       7 (V: 47.58%) (N:  2.37%) PV: Q4 D16 C17 D17
avr. 04, 2018 11:55:28 AM com.gokgs.client.gtp.GtpClient protocolEvent
GRAVE: EOF from engine in the middle of a game! Shutting down.
java.io.EOFException
        at java.io.DataInputStream.readShort(Unknown Source)
        at org.igoweb.igoweb.client.Conn.waitForMessages(Conn.java:302)
        at java.lang.Thread.run(Unknown Source)
avr. 04, 2018 11:55:28 AM com.gokgs.client.gtp.GtpClient clientEvent
PR╔CIS: Normal disconnection from server.
```

**Comment by MartinDevelopment** [comment]
KGS is just broken.

**Comment by gcp** [comment]
This used to work in old kgsGtp versions. You can probably use --quiet move to work around it. In any case, not a Leela bug.
