### ISSUE TITLE
parse.py InvalidArgumentError

### ISSUE THREAD

**Issue by OmnipotentEntity** [gcp/leela-zero#1691]
Perhaps I am doing something wrong?

```
$ ./parse.py ../../../lz-training/recent/train_
Training with 2982 chunks, validating on 331 chunks
Using 38 worker processes.
Using 38 worker processes.
WARNING:tensorflow:From /home/omnipotententity/work/leela-zero/training/tf/tfprocess.py:311: softmax_cross_entropy_with_logits (from tensorflow.python.ops.nn_ops) is deprecated and will be removed in a future version.
Instructions for updating:

Future major versions of TensorFlow will allow gradients to flow
into the labels input on backprop by default.

See @{tf.nn.softmax_cross_entropy_with_logits_v2}.

WARNING:tensorflow:From /home/omnipotententity/work/leela-zero/training/tf/tfprocess.py:295: calling expand_dims (from tensorflow.python.ops.array_ops) with dim is deprecated and will be removed in a future version.
Instructions for updating:
Use the `axis` argument instead
2018-08-03 09:08:21.033200: E tensorflow/core/common_runtime/executor.cc:696] Executor failed to create kernel. Invalid argument: Conv2DCustomBackpropInputOp only supports NHWC.
         [[Node: tower_0/gradients/tower_0/Conv2D_13_grad/Conv2DBackpropInput = Conv2DBackpropInput[T=DT_FLOAT, _class=["loc:@tower_0/gradients/AddN_8"], data_format="NCHW", dilations=[1, 1, 1, 1], padding="SAME", strides=[1, 1, 1, 1], use_cudnn_on_gpu=true, _device="/job:localhost/replica:0/task:0/device:CPU:0"](ConstantFolding/tower_0/gradients/tower_0/Conv2D_13_grad/ShapeN-matshapes-0, policy_head/read, tower_0/gradients/AddN_3)]]
Traceback (most recent call last):
  File "/home/omnipotententity/.local/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1322, in _do_call
    return fn(*args)
  File "/home/omnipotententity/.local/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1307, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/home/omnipotententity/.local/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1409, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Conv2DCustomBackpropInputOp only supports NHWC.
         [[Node: tower_0/gradients/tower_0/Conv2D_13_grad/Conv2DBackpropInput = Conv2DBackpropInput[T=DT_FLOAT, _class=["loc:@tower_0/gradients/AddN_8"], data_format="NCHW", dilations=[1, 1, 1, 1], padding="SAME", strides=[1, 1, 1, 1], use_cudnn_on_gpu=true, _device="/job:localhost/replica:0/task:0/device:CPU:0"](ConstantFolding/tower_0/gradients/tower_0/Conv2D_13_grad/ShapeN-matshapes-0, policy_head/read, tower_0/gradients/AddN_3)]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./parse.py", line 166, in <module>
    main()
  File "./parse.py", line 162, in main
    tfprocess.process(train_parser, test_parser)
  File "/home/omnipotententity/work/leela-zero/training/tf/tfprocess.py", line 404, in process
    losses = self.measure_loss(batch, training=True)
  File "/home/omnipotententity/work/leela-zero/training/tf/tfprocess.py", line 392, in measure_loss
    self.winner: batch[2]})
  File "/home/omnipotententity/.local/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 900, in run
    run_metadata_ptr)
  File "/home/omnipotententity/.local/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1135, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/omnipotententity/.local/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1316, in _do_run
    run_metadata)
  File "/home/omnipotententity/.local/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1335, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Conv2DCustomBackpropInputOp only supports NHWC.
         [[Node: tower_0/gradients/tower_0/Conv2D_13_grad/Conv2DBackpropInput = Conv2DBackpropInput[T=DT_FLOAT, _class=["loc:@tower_0/gradients/AddN_8"], data_format="NCHW", dilations=[1, 1, 1, 1], padding="SAME", strides=[1, 1, 1, 1], use_cudnn_on_gpu=true, _device="/job:localhost/replica:0/task:0/device:CPU:0"](ConstantFolding/tower_0/gradients/tower_0/Conv2D_13_grad/ShapeN-matshapes-0, policy_head/read, tower_0/gradients/AddN_3)]]

Caused by op 'tower_0/gradients/tower_0/Conv2D_13_grad/Conv2DBackpropInput', defined at:
  File "./parse.py", line 166, in <module>
    main()
  File "./parse.py", line 156, in main
    macrobatch=BATCH_SIZE // RAM_BATCH_SIZE)
  File "/home/omnipotententity/work/leela-zero/training/tf/tfprocess.py", line 164, in init
    self.init_net(planes, probs, winner, gpus_num)
  File "/home/omnipotententity/work/leela-zero/training/tf/tfprocess.py", line 198, in init_net
    grads = opt.compute_gradients(loss)
  File "/home/omnipotententity/.local/lib/python3.6/site-packages/tensorflow/python/training/optimizer.py", line 511, in compute_gradients
    colocate_gradients_with_ops=colocate_gradients_with_ops)
  File "/home/omnipotententity/.local/lib/python3.6/site-packages/tensorflow/python/ops/gradients_impl.py", line 532, in gradients
    gate_gradients, aggregation_method, stop_gradients)
  File "/home/omnipotententity/.local/lib/python3.6/site-packages/tensorflow/python/ops/gradients_impl.py", line 701, in _GradientsHelper
    lambda: grad_fn(op, *out_grads))
  File "/home/omnipotententity/.local/lib/python3.6/site-packages/tensorflow/python/ops/gradients_impl.py", line 396, in _MaybeCompile
    return grad_fn()  # Exit early
  File "/home/omnipotententity/.local/lib/python3.6/site-packages/tensorflow/python/ops/gradients_impl.py", line 701, in <lambda>
    lambda: grad_fn(op, *out_grads))
  File "/home/omnipotententity/.local/lib/python3.6/site-packages/tensorflow/python/ops/nn_grad.py", line 520, in _Conv2DGrad
    data_format=data_format),
  File "/home/omnipotententity/.local/lib/python3.6/site-packages/tensorflow/python/ops/gen_nn_ops.py", line 1228, in conv2d_backprop_input
    dilations=dilations, name=name)
  File "/home/omnipotententity/.local/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/home/omnipotententity/.local/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3414, in create_op
    op_def=op_def)
  File "/home/omnipotententity/.local/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1740, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

...which was originally created as op 'tower_0/Conv2D_13', defined at:
  File "./parse.py", line 166, in <module>
    main()
[elided 1 identical lines from previous traceback]
  File "/home/omnipotententity/work/leela-zero/training/tf/tfprocess.py", line 164, in init
    self.init_net(planes, probs, winner, gpus_num)
  File "/home/omnipotententity/work/leela-zero/training/tf/tfprocess.py", line 191, in init_net
    self.sx[i], self.sy_[i], self.sz_[i])
  File "/home/omnipotententity/work/leela-zero/training/tf/tfprocess.py", line 307, in tower_loss
    y_conv, z_conv = self.construct_net(x)
  File "/home/omnipotententity/work/leela-zero/training/tf/tfprocess.py", line 585, in construct_net
    name="policy_head")
  File "/home/omnipotententity/work/leela-zero/training/tf/tfprocess.py", line 537, in conv_block
    net = conv2d(net, W_conv)
  File "/home/omnipotententity/work/leela-zero/training/tf/tfprocess.py", line 46, in conv2d
    strides=[1, 1, 1, 1], padding='SAME')
  File "/home/omnipotententity/.local/lib/python3.6/site-packages/tensorflow/python/ops/gen_nn_ops.py", line 956, in conv2d
    data_format=data_format, dilations=dilations, name=name)
  File "/home/omnipotententity/.local/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/home/omnipotententity/.local/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3414, in create_op
    op_def=op_def)
  File "/home/omnipotententity/.local/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1740, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

InvalidArgumentError (see above for traceback): Conv2DCustomBackpropInputOp only supports NHWC.
         [[Node: tower_0/gradients/tower_0/Conv2D_13_grad/Conv2DBackpropInput = Conv2DBackpropInput[T=DT_FLOAT, _class=["loc:@tower_0/gradients/AddN_8"], data_format="NCHW", dilations=[1, 1, 1, 1], padding="SAME", strides=[1, 1, 1, 1], use_cudnn_on_gpu=true, _device="/job:localhost/replica:0/task:0/device:CPU:0"](ConstantFolding/tower_0/gradients/tower_0/Conv2D_13_grad/ShapeN-matshapes-0, policy_head/read, tower_0/gradients/AddN_3)]]
```

**Comment by Ttl** [comment]
You have Tensorflow with only CPU support which isn't supported by the LZ training code. Try `pip3 install tensorflow-gpu`.

**Comment by OmnipotentEntity** [comment]
Now that I have `tensorflow-gpu` installed I get farther but I segfault.  (It should be mentioned that because I'm running Ubuntu 18.04, I only have access to CUDA 9.1, so I had to custom compile the pip package.)

Here is my output:

```
Training with 2982 chunks, validating on 331 chunks                                                                                                                 
Using 38 worker processes.                                                                                                                                          
Using 38 worker processes.                                                                                                                                          
2018-08-03 22:36:04.566005: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1392] Found device 0 with properties:                                                
name: GeForce GTX 780 Ti major: 3 minor: 5 memoryClockRate(GHz): 0.928                                                                                              
pciBusID: 0000:04:00.0                                                                                                                                              
totalMemory: 3.00GiB freeMemory: 2.13GiB                                                                                                                            
2018-08-03 22:36:04.726542: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1392] Found device 1 with properties:                                                
name: GeForce GTX 780 Ti major: 3 minor: 5 memoryClockRate(GHz): 0.928                                                                                            
pciBusID: 0000:83:00.0                                                                                                                                            
totalMemory: 3.00GiB freeMemory: 2.06GiB                                                                                                                          
2018-08-03 22:36:04.726632: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1471] Adding visible gpu devices: 0, 1                                             
2018-08-03 22:36:05.418025: I tensorflow/core/common_runtime/gpu/gpu_device.cc:952] Device interconnect StreamExecutor with strength 1 edge matrix:               
2018-08-03 22:36:05.418105: I tensorflow/core/common_runtime/gpu/gpu_device.cc:958]      0 1                                                                      
2018-08-03 22:36:05.418117: I tensorflow/core/common_runtime/gpu/gpu_device.cc:971] 0:   N N                                                                      
2018-08-03 22:36:05.418127: I tensorflow/core/common_runtime/gpu/gpu_device.cc:971] 1:   N N                                                                      
2018-08-03 22:36:05.418418: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1084] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 2457 MB memory) -> physical GPU (device: 0, name: GeForce GTX
780 Ti, pci bus id: 0000:04:00.0, compute capability: 3.5)                                                                                                                                                               
2018-08-03 22:36:05.419103: E tensorflow/stream_executor/cuda/cuda_driver.cc:903] failed to allocate 2.40G (2576508416 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY
2018-08-03 22:36:05.419290: E tensorflow/stream_executor/cuda/cuda_driver.cc:903] failed to allocate 2.16G (2318857472 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY
2018-08-03 22:36:05.461242: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1084] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:1 with 2457 MB memory) -> physical GPU (device: 1, name: GeForce GTX
780 Ti, pci bus id: 0000:83:00.0, compute capability: 3.5)                         
2018-08-03 22:36:05.461914: E tensorflow/stream_executor/cuda/cuda_driver.cc:903] failed to allocate 2.40G (2576508416 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY
2018-08-03 22:36:05.462093: E tensorflow/stream_executor/cuda/cuda_driver.cc:903] failed to allocate 2.16G (2318857472 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY
2018-08-03 22:36:05.462268: E tensorflow/stream_executor/cuda/cuda_driver.cc:903] failed to allocate 1.94G (2086971648 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY
2018-08-03 22:36:05.462442: E tensorflow/stream_executor/cuda/cuda_driver.cc:903] failed to allocate 1.75G (1878274560 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY                                                    
2018-08-03 22:36:05.462623: E tensorflow/stream_executor/cuda/cuda_driver.cc:903] failed to allocate 1.57G (1690447104 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY                                                            
2018-08-03 22:36:05.462805: E tensorflow/stream_executor/cuda/cuda_driver.cc:903] failed to allocate 1.42G (1521402368 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY                                                            
2018-08-03 22:36:05.462973: E tensorflow/stream_executor/cuda/cuda_driver.cc:903] failed to allocate 1.27G (1369262080 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY                                                         
2018-08-03 22:36:05.463151: E tensorflow/stream_executor/cuda/cuda_driver.cc:903] failed to allocate 1.15G (1232335872 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY
2018-08-03 22:36:05.462973: E tensorflow/stream_executor/cuda/cuda_driver.cc:903] failed to allocate 1.27G (1369262080 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY                                                   [315/1816]
2018-08-03 22:36:05.463151: E tensorflow/stream_executor/cuda/cuda_driver.cc:903] failed to allocate 1.15G (1232335872 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY
2018-08-03 22:36:05.463320: E tensorflow/stream_executor/cuda/cuda_driver.cc:903] failed to allocate 1.03G (1109102336 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY
2018-08-03 22:36:05.463492: E tensorflow/stream_executor/cuda/cuda_driver.cc:903] failed to allocate 951.95M (998192128 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY
2018-08-03 22:36:05.463662: E tensorflow/stream_executor/cuda/cuda_driver.cc:903] failed to allocate 856.75M (898372864 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY
2018-08-03 22:36:05.463832: E tensorflow/stream_executor/cuda/cuda_driver.cc:903] failed to allocate 771.08M (808535552 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY
2018-08-03 22:36:05.464001: E tensorflow/stream_executor/cuda/cuda_driver.cc:903] failed to allocate 693.97M (727682048 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY
2018-08-03 22:36:05.464171: E tensorflow/stream_executor/cuda/cuda_driver.cc:903] failed to allocate 624.57M (654914048 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY
2018-08-03 22:36:05.464340: E tensorflow/stream_executor/cuda/cuda_driver.cc:903] failed to allocate 562.12M (589422848 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY
2018-08-03 22:36:05.464508: E tensorflow/stream_executor/cuda/cuda_driver.cc:903] failed to allocate 505.91M (530480640 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY
2018-08-03 22:36:05.464675: E tensorflow/stream_executor/cuda/cuda_driver.cc:903] failed to allocate 455.31M (477432576 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY
2018-08-03 22:36:05.464854: E tensorflow/stream_executor/cuda/cuda_driver.cc:903] failed to allocate 409.78M (429689344 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY
2018-08-03 22:36:05.465029: E tensorflow/stream_executor/cuda/cuda_driver.cc:903] failed to allocate 368.80M (386720512 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY
2018-08-03 22:36:05.465200: E tensorflow/stream_executor/cuda/cuda_driver.cc:903] failed to allocate 331.92M (348048640 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY                                                           
2018-08-03 22:36:05.465369: E tensorflow/stream_executor/cuda/cuda_driver.cc:903] failed to allocate 298.73M (313243904 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY                                                           
2018-08-03 22:36:05.465538: E tensorflow/stream_executor/cuda/cuda_driver.cc:903] failed to allocate 268.86M (281919744 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY                                                           
2018-08-03 22:36:05.465707: E tensorflow/stream_executor/cuda/cuda_driver.cc:903] failed to allocate 241.97M (253728000 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY                                                           
2018-08-03 22:36:05.465876: E tensorflow/stream_executor/cuda/cuda_driver.cc:903] failed to allocate 217.78M (228355328 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY
2018-08-03 22:36:05.466045: E tensorflow/stream_executor/cuda/cuda_driver.cc:903] failed to allocate 196.00M (205519872 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY
2018-08-03 22:36:05.466214: E tensorflow/stream_executor/cuda/cuda_driver.cc:903] failed to allocate 176.40M (184967936 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY
2018-08-03 22:36:05.466383: E tensorflow/stream_executor/cuda/cuda_driver.cc:903] failed to allocate 158.76M (166471168 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY
2018-08-03 22:36:05.466552: E tensorflow/stream_executor/cuda/cuda_driver.cc:903] failed to allocate 142.88M (149824256 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY
2018-08-03 22:36:05.466721: E tensorflow/stream_executor/cuda/cuda_driver.cc:903] failed to allocate 128.59M (134841856 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY
2018-08-03 22:36:05.466899: E tensorflow/stream_executor/cuda/cuda_driver.cc:903] failed to allocate 115.74M (121357824 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY
2018-08-03 22:36:05.467083: E tensorflow/stream_executor/cuda/cuda_driver.cc:903] failed to allocate 104.16M (109222144 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY
2018-08-03 22:36:05.467266: E tensorflow/stream_executor/cuda/cuda_driver.cc:903] failed to allocate 93.75M (98300160 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY
2018-08-03 22:36:05.467451: E tensorflow/stream_executor/cuda/cuda_driver.cc:903] failed to allocate 84.37M (88470272 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY
2018-08-03 22:36:05.467632: E tensorflow/stream_executor/cuda/cuda_driver.cc:903] failed to allocate 75.93M (79623424 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY
2018-08-03 22:36:05.467813: E tensorflow/stream_executor/cuda/cuda_driver.cc:903] failed to allocate 68.34M (71661312 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY
2018-08-03 22:36:05.467998: E tensorflow/stream_executor/cuda/cuda_driver.cc:903] failed to allocate 61.51M (64495360 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY
2018-08-03 22:36:05.468185: E tensorflow/stream_executor/cuda/cuda_driver.cc:903] failed to allocate 55.36M (58045952 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY
2018-08-03 22:36:05.468364: E tensorflow/stream_executor/cuda/cuda_driver.cc:903] failed to allocate 49.82M (52241408 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY
2018-08-03 22:36:05.468548: E tensorflow/stream_executor/cuda/cuda_driver.cc:903] failed to allocate 44.84M (47017472 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY
2018-08-03 22:36:05.468805: E tensorflow/stream_executor/cuda/cuda_driver.cc:903] failed to allocate 40.36M (42315776 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY                                                             
WARNING:tensorflow:From /home/omnipotententity/work/leela-zero/training/tf/tfprocess.py:311: softmax_cross_entropy_with_logits (from tensorflow.python.ops.nn_ops) is deprecated and will be removed in a future version.
Instructions for updating:                                                                                                                                         
                                                                                                                                                                   
Future major versions of TensorFlow will allow gradients to flow                                                                                                                                                               
into the labels input on backprop by default.                                      
                                                                                                                                                                   
See @{tf.nn.softmax_cross_entropy_with_logits_v2}.                                                                                                                 
                                                                                                                                                                   
WARNING:tensorflow:From /home/omnipotententity/work/leela-zero/training/tf/tfprocess.py:295: calling expand_dims (from tensorflow.python.ops.array_ops) with dim is deprecated and will be removed in a future version.
Instructions for updating:                                                                                                                                                                                                     
Use the `axis` argument instead                                                                                                                                                                                                
2018-08-03 22:41:09.319424: E tensorflow/stream_executor/cuda/cuda_blas.cc:459] failed to create cublas handle: CUBLAS_STATUS_NOT_INITIALIZED                                                                               
2018-08-03 22:41:09.320154: E tensorflow/stream_executor/cuda/cuda_blas.cc:459] failed to create cublas handle: CUBLAS_STATUS_NOT_INITIALIZED
2018-08-03 22:41:09.319424: E tensorflow/stream_executor/cuda/cuda_blas.cc:459] failed to create cublas handle: CUBLAS_STATUS_NOT_INITIALIZED                                                                         [270/1816]
2018-08-03 22:41:09.320154: E tensorflow/stream_executor/cuda/cuda_blas.cc:459] failed to create cublas handle: CUBLAS_STATUS_NOT_INITIALIZED                      
2018-08-03 22:41:09.323152: E tensorflow/stream_executor/cuda/cuda_blas.cc:459] failed to create cublas handle: CUBLAS_STATUS_NOT_INITIALIZED                      
2018-08-03 22:41:09.339284: E tensorflow/stream_executor/cuda/cuda_driver.cc:965] failed to alloc 16777216 bytes on host: CUDA_ERROR_OUT_OF_MEMORY                  
2018-08-03 22:41:09.339332: W ./tensorflow/core/common_runtime/gpu/pool_allocator.h:195] could not allocate pinned host memory of size: 16777216                    
2018-08-03 22:41:09.470391: E tensorflow/stream_executor/cuda/cuda_blas.cc:459] failed to create cublas handle: CUBLAS_STATUS_NOT_INITIALIZED                       
2018-08-03 22:41:09.470762: E tensorflow/stream_executor/cuda/cuda_blas.cc:459] failed to create cublas handle: CUBLAS_STATUS_NOT_INITIALIZED                       
2018-08-03 22:41:09.471703: E tensorflow/stream_executor/cuda/cuda_blas.cc:459] failed to create cublas handle: CUBLAS_STATUS_NOT_INITIALIZED                       
2018-08-03 22:41:09.472050: E tensorflow/stream_executor/cuda/cuda_blas.cc:459] failed to create cublas handle: CUBLAS_STATUS_NOT_INITIALIZED                       
2018-08-03 22:41:09.472624: E tensorflow/stream_executor/cuda/cuda_blas.cc:459] failed to create cublas handle: CUBLAS_STATUS_NOT_INITIALIZED                       
2018-08-03 22:41:09.472980: E tensorflow/stream_executor/cuda/cuda_blas.cc:459] failed to create cublas handle: CUBLAS_STATUS_NOT_INITIALIZED                       
2018-08-03 22:41:09.482669: E tensorflow/stream_executor/cuda/cuda_dnn.cc:332] could not create cudnn handle: CUDNN_STATUS_INTERNAL_ERROR                           
[1]    36732 segmentation fault (core dumped)  ./parse.py --train ../../../lz-training/recent/train_
```

After that is a mess of BrokenPipeErrors for each thread spawned (76 in total)

**Comment by Ttl** [comment]
As the logs say`CUDA_ERROR_OUT_OF_MEMORY`, you are running out of GPU memory. Decrease the batch size in `parse.py` until it works or try a smaller network size.

**Comment by OmnipotentEntity** [comment]
It said that the smallest sane size is 64.  I tried both 64 and 32 (and per issue #52, I also adjusted the learning rate in the MomentumOptimizer) and I still get CUDA out of memory errors.

Any idea what I'm doing wrong?

**Comment by Ttl** [comment]
Try setting `BATCH_SIZE` and `RAM_BATCH_SIZE` in `parse.py` to 8 and `shuffle_size` on lines 144 and 149 to `1<<14`.

Since it looks like you have two GPUs change `gpus_num` in `tfprocess.py` to 2.

Keep the default network size of 6x128.

Do these settings work? Undo the shuffle_size change if they do and then try raising the batch size.

**Comment by OmnipotentEntity** [comment]
It still goes out of memory, I suppose I have something wrong with my setup, possibly stemming to needing to compile tf from scratch and having something subtly wrong.  I'll double check that.

**Comment by Ttl** [comment]
I just realized that it's probably because the code tries to allocate 80% of GPU memory, but you don't have that much free. Try changing `per_process_gpu_memory_fraction` in tfprocess.py:134.

**Comment by tterava** [comment]
You could also try
```
config = tf.ConfigProto()
config.gpu_options.allow_growth = True
session = tf.Session(config=config, ...)
```

**Comment by chunjiongzhang** [comment]
I have the same problem. Have you solved it thoroughly?  please guild me  how to solve it

**Comment by chunjiongzhang** [comment]
@tterava @Ttl

**Comment by gcp** [comment]
Please file a new issue with the actual errors you are getting. The fixes given here solved the original problem.
