### ISSUE TITLE
leela on mac

### ISSUE THREAD

**Issue by ranamar16** [gcp/leela-zero#1864]
I'm trying to run lizzie/goReviewPartner, the program is going up, but stay with the message leela-zero is loading/No permission(error 13), when i check the terminal, i can see the "./leelaz" has no permission, how do i solve it?

java.io.IOException: Cannot run program "./leelaz" (in directory "."): error=13, Permission denied
at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
at featurecat.lizzie.analysis.Leelaz.(Leelaz.java:96)
at featurecat.lizzie.Lizzie.lambda$main$0(Lizzie.java:38)
at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: error=13, Permission denied
at java.lang.UNIXProcess.forkAndExec(Native Method)
at java.lang.UNIXProcess.(UNIXProcess.java:247)
at java.lang.ProcessImpl.start(ProcessImpl.java:134)
at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
... 3 more

**Comment by maxinjapan** [comment]
@ranamar16 can you be more specific about the problem? What error you get after you change the permission?  

This is what my lizzie 0.5 folder looks like on a macOS Sierra 10.12.6 and everything works fine:  

<img width="635" alt="screenshot 2018-09-22 19 31 00" src="https://user-images.githubusercontent.com/32621200/45920581-1e769c00-be9e-11e8-87c2-51cfac240def.png">

**Comment by ranamar16** [comment]
hey, the lizzie going up, but stack on the "leela zero is loading...", in the terminal i get this error:

java.io.IOException: Cannot run program "./leelaz" (in directory "."): error=13, Permission denied
at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
at featurecat.lizzie.analysis.Leelaz.(Leelaz.java:96)
at featurecat.lizzie.Lizzie.lambda$main$0(Lizzie.java:38)
at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: error=13, Permission denied
at java.lang.UNIXProcess.forkAndExec(Native Method)
at java.lang.UNIXProcess.(UNIXProcess.java:247)
at java.lang.ProcessImpl.start(ProcessImpl.java:134)
at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
... 3 more

(the error does not change after fixing the permission)

my lizzie folder looks like this:

Rans-MacBook-Pro:lizzie ranamar$ ls -al
total 262672
drwxrwxrwx@ 13 ranamar  staff       442 Sep 22 21:47 .
drwx------+ 89 ranamar  staff      3026 Sep 22 02:46 ..
-rwxr-xr-x@  1 ranamar  staff      6148 Sep 22 21:47 .DS_Store
-rwxrwxrwx@  1 ranamar  staff    413288 Jun  1 01:16 Lizzie.jar
-rwxr-xr-x   1 ranamar  staff    359705 Sep 22 00:47 Lizzie.jar.cpgz
drwxrwxr-x@  6 ranamar  staff       204 Jun  1 00:28 assets
-rwxr-xr-x   1 ranamar  staff  93608093 Sep 22 01:42 best-network
-rwxr-xr-x   1 ranamar  staff       949 Sep 21 23:38 config.txt
drwxrwxrwx@ 21 ranamar  staff       714 Sep 21 23:48 leelaz
-rwxrwxr-x@  1 ranamar  staff  40075485 Jun  1 00:04 network.gz
-rwxr-xr-x   1 ranamar  staff        35 Sep 22 03:00 persist
drwxr-xr-x   2 ranamar  staff        68 Sep 21 23:38 plugin
-rwxrwxr-x@  1 ranamar  staff      6509 Jun  1 00:52 readme.txt

**Comment by maxinjapan** [comment]
Leelaz seems to be a directory

**Comment by roy7** [comment]
It should be the executable leelaz program, not a directory.
