### ISSUE TITLE
how long it takes to training a game on i5 cpu?

### ISSUE THREAD

**Issue by l1t1** [gcp/leela-zero#1954]
I dump a sgf that includes one game 
```
D:\tool\leela15>leelaz -w networks/2da87ea8da0f54e87b70159e6bb82811b61d1c31091b6e019fbe62aeaa803b9c
...
Leela: dump_supervised 1c192935500bfa07d47eeb765316c0851ddf62bf11e97d4ee8fe6af20bf46935.sgf train.txt
Total games in file: 1
Shuffling...done.
Dumped 102 training positions.
Writing chunk 0

```
then run follwing command
```
C:\Python37>python C:\Users\aaa\Downloads\leela-zero-0.15\training/tf/parse.py D:\tool\leela15\train.txt.0
Training with 1 chunks, validating on 0 chunks
Using 2 worker processes.
Using 2 worker processes.
2018-10-25 16:44:11.843479: I d:\build\tensorflow\tensorflow-r1.7\tensorflow\core\platform\cpu_feature_guard.cc:140] You
r CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
WARNING:tensorflow:From C:\Users\aaa\Downloads\leela-zero-0.15\training\tf\tfprocess.py:189: softmax_cross_entropy_wit
h_logits (from tensorflow.python.ops.nn_ops) is deprecated and will be removed in a future version.
Instructions for updating:

Future major versions of TensorFlow will allow gradients to flow
into the labels input on backprop by default.

See tf.nn.softmax_cross_entropy_with_logits_v2.
```
it seems hang on

**Comment by l1t1** [comment]
my software version
python 3.7.1
tensflow 1.7
the sgf i used[http://zero.sjeng.org/viewmatch/1c192935500bfa07d47eeb765316c0851ddf62bf11e97d4ee8fe6af20bf46935.sgf](url)

**Comment by l1t1** [comment]
after 4 minutes, it failed
```
2018-10-25 16:48:42.517679: E d:\build\tensorflow\tensorflow-r1.7\tensorflow\core\common_runtime\executor.cc:644] Execut
or failed to create kernel. Invalid argument: Conv2DCustomBackpropInputOp only supports NHWC.
         [[Node: gradients/Conv2D_14_grad/Conv2DBackpropInput = Conv2DBackpropInput[T=DT_FLOAT, data_format="NCHW", dila
tions=[1, 1, 1, 1], padding="SAME", strides=[1, 1, 1, 1], use_cudnn_on_gpu=true, _device="/job:localhost/replica:0/task:
0/device:CPU:0"](gradients/Conv2D_1_grad/Const, Variable_16/read, gradients/AddN_6)]]
Traceback (most recent call last):
  File "C:\Python37\lib\site-packages\tensorflow\python\client\session.py", line 1327, in _do_call
    return fn(*args)
  File "C:\Python37\lib\site-packages\tensorflow\python\client\session.py", line 1312, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "C:\Python37\lib\site-packages\tensorflow\python\client\session.py", line 1420, in _call_tf_sessionrun
    status, run_metadata)
  File "C:\Python37\lib\site-packages\tensorflow\python\framework\errors_impl.py", line 516, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.InvalidArgumentError: Conv2DCustomBackpropInputOp only supports NHWC.
         [[Node: gradients/Conv2D_14_grad/Conv2DBackpropInput = Conv2DBackpropInput[T=DT_FLOAT, data_format="NCHW", dila
tions=[1, 1, 1, 1], padding="SAME", strides=[1, 1, 1, 1], use_cudnn_on_gpu=true, _device="/job:localhost/replica:0/task:
0/device:CPU:0"](gradients/Conv2D_1_grad/Const, Variable_16/read, gradients/AddN_6)]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\lutao\Downloads\leela-zero-0.15\training/tf/parse.py", line 166, in <module>
    main()
  File "C:\Users\lutao\Downloads\leela-zero-0.15\training/tf/parse.py", line 162, in main
    tfprocess.process(train_parser, test_parser)
  File "C:\Users\lutao\Downloads\leela-zero-0.15\training\tf\tfprocess.py", line 338, in process
    losses = self.measure_loss(batch, training=True)
  File "C:\Users\lutao\Downloads\leela-zero-0.15\training\tf\tfprocess.py", line 326, in measure_loss
    self.winner: batch[2]})
  File "C:\Python37\lib\site-packages\tensorflow\python\client\session.py", line 905, in run
    run_metadata_ptr)
  File "C:\Python37\lib\site-packages\tensorflow\python\client\session.py", line 1140, in _run
    feed_dict_tensor, options, run_metadata)
  File "C:\Python37\lib\site-packages\tensorflow\python\client\session.py", line 1321, in _do_run
    run_metadata)
  File "C:\Python37\lib\site-packages\tensorflow\python\client\session.py", line 1340, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Conv2DCustomBackpropInputOp only supports NHWC.
         [[Node: gradients/Conv2D_14_grad/Conv2DBackpropInput = Conv2DBackpropInput[T=DT_FLOAT, data_format="NCHW", dila
tions=[1, 1, 1, 1], padding="SAME", strides=[1, 1, 1, 1], use_cudnn_on_gpu=true, _device="/job:localhost/replica:0/task:
0/device:CPU:0"](gradients/Conv2D_1_grad/Const, Variable_16/read, gradients/AddN_6)]]

Caused by op 'gradients/Conv2D_14_grad/Conv2DBackpropInput', defined at:
  File "C:\Users\lutao\Downloads\leela-zero-0.15\training/tf/parse.py", line 166, in <module>
    main()
  File "C:\Users\lutao\Downloads\leela-zero-0.15\training/tf/parse.py", line 156, in main
    macrobatch=BATCH_SIZE // RAM_BATCH_SIZE)
  File "C:\Users\lutao\Downloads\leela-zero-0.15\training\tf\tfprocess.py", line 156, in init
    self.init_net(planes, probs, winner)
  File "C:\Users\lutao\Downloads\leela-zero-0.15\training\tf\tfprocess.py", line 217, in init_net
    self.grad_op_real = opt.compute_gradients(self.loss)
  File "C:\Python37\lib\site-packages\tensorflow\python\training\optimizer.py", line 492, in compute_gradients
    colocate_gradients_with_ops=colocate_gradients_with_ops)
  File "C:\Python37\lib\site-packages\tensorflow\python\ops\gradients_impl.py", line 488, in gradients
    gate_gradients, aggregation_method, stop_gradients)
  File "C:\Python37\lib\site-packages\tensorflow\python\ops\gradients_impl.py", line 625, in _GradientsHelper
    lambda: grad_fn(op, *out_grads))
  File "C:\Python37\lib\site-packages\tensorflow\python\ops\gradients_impl.py", line 379, in _MaybeCompile
    return grad_fn()  # Exit early
  File "C:\Python37\lib\site-packages\tensorflow\python\ops\gradients_impl.py", line 625, in <lambda>
    lambda: grad_fn(op, *out_grads))
  File "C:\Python37\lib\site-packages\tensorflow\python\ops\nn_grad.py", line 514, in _Conv2DGrad
    data_format=data_format),
  File "C:\Python37\lib\site-packages\tensorflow\python\ops\gen_nn_ops.py", line 1336, in conv2d_backprop_input
    dilations=dilations, name=name)
  File "C:\Python37\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "C:\Python37\lib\site-packages\tensorflow\python\framework\ops.py", line 3290, in create_op
    op_def=op_def)
  File "C:\Python37\lib\site-packages\tensorflow\python\framework\ops.py", line 1654, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

...which was originally created as op 'Conv2D_14', defined at:
  File "C:\Users\lutao\Downloads\leela-zero-0.15\training/tf/parse.py", line 166, in <module>
    main()
[elided 1 identical lines from previous traceback]
  File "C:\Users\lutao\Downloads\leela-zero-0.15\training\tf\tfprocess.py", line 156, in init
    self.init_net(planes, probs, winner)
  File "C:\Users\lutao\Downloads\leela-zero-0.15\training\tf\tfprocess.py", line 163, in init_net
    self.y_conv, self.z_conv = self.construct_net(self.x)
  File "C:\Users\lutao\Downloads\leela-zero-0.15\training\tf\tfprocess.py", line 516, in construct_net
    output_channels=1)
  File "C:\Users\lutao\Downloads\leela-zero-0.15\training\tf\tfprocess.py", line 461, in conv_block
    net = conv2d(net, W_conv)
  File "C:\Users\lutao\Downloads\leela-zero-0.15\training\tf\tfprocess.py", line 43, in conv2d
    strides=[1, 1, 1, 1], padding='SAME')
  File "C:\Python37\lib\site-packages\tensorflow\python\ops\gen_nn_ops.py", line 1039, in conv2d
    data_format=data_format, dilations=dilations, name=name)
  File "C:\Python37\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "C:\Python37\lib\site-packages\tensorflow\python\framework\ops.py", line 3290, in create_op
    op_def=op_def)
  File "C:\Python37\lib\site-packages\tensorflow\python\framework\ops.py", line 1654, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

InvalidArgumentError (see above for traceback): Conv2DCustomBackpropInputOp only supports NHWC.
         [[Node: gradients/Conv2D_14_grad/Conv2DBackpropInput = Conv2DBackpropInput[T=DT_FLOAT, data_format="NCHW", dila
tions=[1, 1, 1, 1], padding="SAME", strides=[1, 1, 1, 1], use_cudnn_on_gpu=true, _device="/job:localhost/replica:0/task:
0/device:CPU:0"](gradients/Conv2D_1_grad/Const, Variable_16/read, gradients/AddN_6)]]
```

**Comment by ihavnoid** [comment]
AFAIK it requires a slightly different data format for CPUs.  Not sure how much code we need to change... but what are you trying to achieve here?

**Comment by l1t1** [comment]
my gpu type is 730 and is very low, so I want to use cpu

**Comment by gcp** [comment]
Yeah the problem is that TensorFlow is garbage and requires NHWC layouts if you are trying to optimize on the CPU, but our code wants NCHW because that is fastest on GPUs.

Basically training on the CPU is not supported. From my POV this is really a TensorFlow bug.

**Comment by l1t1** [comment]
can modified the use_cudnn_on_gpu=true, to false

**Comment by ihavnoid** [comment]
@l1t1  - I recommend you give up.  The last time I tried, CPU based training was something like 50~100 times slower than GPU based training.  For example, when I first bought my i7-8700 + GTX1080 PC, it took me a couple of minutes to train what took a full day on my i5 laptop.  the leela-zero net is at least 100 times more complex than my first toy neural net.  It is taking at least a whole week to train a 20x256 net on my PC with a single GTX1080 to satisfactory levels.
