### ISSUE TITLE
java.lang.RuntimeException: BAD MOVE: resign

### ISSUE THREAD

**Issue by oTkPoBeHuE** [gcp/leela-zero#306]
![123123](https://user-images.githubusercontent.com/3988741/33782076-6bfb8800-dc81-11e7-914a-e6ba5792dab4.png)
oh noes!!!
```
java.lang.RuntimeException: BAD MOVE: resign
        at leelawatcher.parser.AutoGtpOutputParser.parseMove(AutoGtpOutputParser.java:129)
        at leelawatcher.parser.AutoGtpOutputParser.lambda$start$0(AutoGtpOutputParser.java:90)
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
        at java.util.concurrent.FutureTask.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
```
What is it?

**Comment by Dorus** [comment]
This means leelawatcher is unable to parse the "resign" move. A move that... dum dum dum... means leelaz resigned.

Resigning was recently turned on, i guess this is a bug with leelawatcher so report it with them.

**Comment by FelixBrendel** [comment]
It was actually already fixed. OP seems to be using the old version of leela-watcher.

**Comment by gaieepo** [comment]
Keep the LeelaWatcher up to date through https://github.com/fsparv/LeelaWatcher/releases
