### ISSUE TITLE
Importance of resign data status

### ISSUE THREAD

**Issue by grolich** [gcp/leela-zero#421]
While it is important to not have many false positive resigns, as @gcp pointed out, it might be equally important to not have it so low as to cause Leela Zero to play on in too many positions in which it already predicts the result correctly. 
It isn't just a matter of speeding up the games, it's also a matter of training data usefulness which may cause training to stall a lot earlier:

Playing too long in lost positions which Leela knows are lost generates a lot of positions to be used as training data and are not that helpful and will make training a lot less effective, increasing the chance of a net that hasn't learned for more and more iterations. 

What is the current status of the resign percentage testing for false positives? 
And are there any plans of increasing it? 
Just heard nothing about this for a while, so I was wondering if there are any changes planned with it.

**Comment by isty2e** [comment]
I would like to test it myself, but it takes more than a week to download the required data. I hope someone with the data or fast connection with OGS server would do it someday...

**Comment by killerducky** [comment]
See below an update on my data for the last few networks. I am no longer forcing -r 0 in my local area, so I have far fewer results (only 57 of my local 381 games were run with -r 0 instead of -r 1). Earlier -r 1 was having near 10% incorrect resigns, but now it is 1.8%. 

Going to -r 5 only changes the average game length from 354 to 315 (average with -r 0 is 463), and I don't have enough data to say for sure how safe that is. We are in the middle of quite a few major changes so I propose we don't change anything for now. Longer term I will work on a way to send just a single number to the server for "winner's lowest winrate", and the server can monitor this. 

BTW I need to double check this still works in latest next branch because they changed the matches to also save the debug files (previously only self plays did that). I think by luck it will work because matches always have -r 1, so the script ignores them.

```
Resign rate: 0.05
Black won 33/57 (57.89%)
Of games Black won:
    Incorrect uct resigns = 2/33 (6.06%)
    Correct uct resigns = 28/33 (84.85%)
    No Resign = 3/33 (9.09%)
    Average game length = 463. Average game length with resigns = 329 (28.84% reduction)
Of games White won:
    Incorrect uct resigns = 0/24 (0.00%)
    Correct uct resigns = 21/24 (87.50%)
    No Resign = 3/24 (12.50%)
    Average game length = 423. Average game length with resigns = 296 (30.06% reduction)
Of all games:
    Incorrect uct resigns = 2/57 (3.51%)
    Correct uct resigns = 49/57 (85.96%)
    No Resign = 6/57 (10.53%)
    Average game length = 446. Average game length with resigns = 315 (29.33% reduction)

Resign rate: 0.02
Black won 33/57 (57.89%)
Of games Black won:
    Incorrect uct resigns = 1/33 (3.03%)
    Correct uct resigns = 25/33 (75.76%)
    No Resign = 7/33 (21.21%)
    Average game length = 463. Average game length with resigns = 354 (23.46% reduction)
Of games White won:
    Incorrect uct resigns = 0/24 (0.00%)
    Correct uct resigns = 18/24 (75.00%)
    No Resign = 6/24 (25.00%)
    Average game length = 423. Average game length with resigns = 316 (25.39% reduction)
Of all games:
    Incorrect uct resigns = 1/57 (1.75%)
    Correct uct resigns = 43/57 (75.44%)
    No Resign = 13/57 (22.81%)
    Average game length = 446. Average game length with resigns = 338 (24.23% reduction)

Resign rate: 0.01
Black won 33/57 (57.89%)
Of games Black won:
    Incorrect uct resigns = 1/33 (3.03%)
    Correct uct resigns = 25/33 (75.76%)
    No Resign = 7/33 (21.21%)
    Average game length = 463. Average game length with resigns = 367 (20.72% reduction)
Of games White won:
    Incorrect uct resigns = 0/24 (0.00%)
    Correct uct resigns = 17/24 (70.83%)
    No Resign = 7/24 (29.17%)
    Average game length = 423. Average game length with resigns = 336 (20.67% reduction)
Of all games:
    Incorrect uct resigns = 1/57 (1.75%)
    Correct uct resigns = 42/57 (73.68%)
    No Resign = 14/57 (24.56%)
    Average game length = 446. Average game length with resigns = 354 (20.70% reduction)
```

**Comment by Dorus** [comment]
Would it be possible to also check how many games ended with the wrong winner because of passes? 3-6% error rate sounds bad, but i have the feeling Leela sometimes lose won games because of incorrect (premature) passes. In this games winrate is actually correct so she would have resigned correctly. It would be good to have stats on this category of games too. It might flip some of the wrong resignations over to correct.

Oh also 57 games is way too few, you need at least 10x as much :) Can you retrieve some games from the server?

**Comment by grolich** [comment]
Actually 3-6% doesn't sound bad at all to me considering anything below 5% was ok on deepmind's end.

The interesting thing is, it wouldn't just speed up the running time by over 10% in your example of going to -r 5 (10% will be used as an easy example even though it's more), there's a hidden effect which we can't measure:
it would create a substantially higher quality training data for LZ by removing a substantial amount of positions in which LZ already knows how it will fare.

How much would such better training data help is hard to tell, but it can have anything from a small to massive effect on the training results (after taking a bit of time for the shorter games to replace the older and longer training data (not sure how many of the past games are used right now for training data generation)).

**Comment by isty2e** [comment]
@killerducky Could you tell us how it has changed for recent networks? I'd love to see what the current state is.

**Comment by bood** [comment]
Yes, if everything works okay, shall we change back to `-r 5` again? it helps improve the game speed.

**Comment by killerducky** [comment]
No we cannot go to `-r 5`, in fact `-r 1` is getting 9% incorrect resigns, higher than the target 5%. This is over my games from Dec 19 till now. Stats for just the past 7 days gives similar results.

```
Resign rate: 0.05
Black won 116/233 (49.79%)
Of games Black won:
    Incorrect uct resigns = 15/116 (12.93%)
    Correct uct resigns = 100/116 (86.21%)
    No Resign = 1/116 (0.86%)
    Average game length = 500. Average game length with resigns = 283 (43.26% reduction)
Of games White won:
    Incorrect uct resigns = 11/117 (9.40%)
    Correct uct resigns = 102/117 (87.18%)
    No Resign = 4/117 (3.42%)
    Average game length = 474. Average game length with resigns = 289 (39.00% reduction)
Of all games:
    Incorrect uct resigns = 26/233 (11.16%)
    Correct uct resigns = 202/233 (86.70%)
    No Resign = 5/233 (2.15%)
    Average game length = 487. Average game length with resigns = 286 (41.18% reduction)

Resign rate: 0.02
Black won 116/233 (49.79%)
Of games Black won:
    Incorrect uct resigns = 14/116 (12.07%)
    Correct uct resigns = 98/116 (84.48%)
    No Resign = 4/116 (3.45%)
    Average game length = 500. Average game length with resigns = 304 (39.11% reduction)
Of games White won:
    Incorrect uct resigns = 10/117 (8.55%)
    Correct uct resigns = 94/117 (80.34%)
    No Resign = 13/117 (11.11%)
    Average game length = 474. Average game length with resigns = 310 (34.46% reduction)
Of all games:
    Incorrect uct resigns = 24/233 (10.30%)
    Correct uct resigns = 192/233 (82.40%)
    No Resign = 17/233 (7.30%)
    Average game length = 487. Average game length with resigns = 307 (36.84% reduction)

Resign rate: 0.01
Black won 116/233 (49.79%)
Of games Black won:
    Incorrect uct resigns = 11/116 (9.48%)
    Correct uct resigns = 95/116 (81.90%)
    No Resign = 10/116 (8.62%)
    Average game length = 500. Average game length with resigns = 315 (36.90% reduction)
Of games White won:
    Incorrect uct resigns = 10/117 (8.55%)
    Correct uct resigns = 85/117 (72.65%)
    No Resign = 22/117 (18.80%)
    Average game length = 474. Average game length with resigns = 321 (32.13% reduction)
Of all games:
    Incorrect uct resigns = 21/233 (9.01%)
    Correct uct resigns = 180/233 (77.25%)
    No Resign = 32/233 (13.73%)
    Average game length = 487. Average game length with resigns = 318 (34.57% reduction)
```

**Comment by MartinDevelopment** [comment]
How come the incorrect resigns increased from before?

**Comment by billyswong** [comment]
The incorrect resign rate has become high enough to be able to give mislead result of test matches already.

**Comment by Dorus** [comment]
On eval games it does little damage because networks that resign incorrectly will only hurt themselves and not pass.

On self part it does hurt because correct loses are required to train away the incorrect resignations.

As long as there are enough games played with resign turned off to train away mistakes, everything is fine, but as the rate has been going up im a little worried it's training in the wrong direction. 

Possibly we need a higher percentage with resign turned off, or need to start supporting 0.5% resign rate.

Another possibility is that the last test did not contain enough games. The current test has more and is more reliable.

**Comment by MartinDevelopment** [comment]
I think we need to retest the incorrect resign rate, with 70 games I only got 4.69% incorrect resign at 15% resign rate

**Comment by killerducky** [comment]
@MartinDevelopment are you on the next branch? You need this commit or the results will be invalid:

```
commit 999ca5d78ba0ca388f4ae93f2323ea5890a9b3e1
Author: Andy Olsen <andy.olsen.tx@gmail.com>
Date:   Sat Dec 9 12:47:52 2017 -0600
```

If you're using that version can you post the output of the script here?

**Comment by MartinDevelopment** [comment]
@killerducky When I try to run that I get an error.
`Traceback (most recent call last):
  File "resign_analysis.py", line 167, in <module>
    gsd = parseGames(args.data, resignrate, args.verbose)
  File "resign_analysis.py", line 59, in parseGames
    assert version == "1\n"
AssertionError
`
Mabye this is because I have .debug.txt.0 files while the scripts says I need to have .txt.debug.0 files?

**Comment by killerducky** [comment]
That means your debug data files were generated from the master branch. You need to delete the debug files that are version 1 and only keep those with version 2 (first line of the debug file).

Yes the names of the files also changed from version 1 to version 2.

**Comment by MartinDevelopment** [comment]
@killerducky Do you meant the opposite? Because all my debug files are version 2 and are generated from the master branch.

**Comment by killerducky** [comment]
Oh I read the error wrong. Looks like it's your resign_analysis.py that is out of date. It should say "assert version == 2".

https://github.com/gcp/leela-zero/blob/next/scripts/resign_analysis/resign_analysis.py#L94

**Comment by MartinDevelopment** [comment]
`Total games to analyze: 260
Resign rate: 0.50
Black won 98/216 (45.37%)
Of games Black won:
    Incorrect uct resigns = 3/98 (3.06%)
    Correct uct resigns = 95/98 (96.94%)
    No Resign = 0/98 (0.00%)
    Average game length = 451. Average game length with resigns = 2 (99.53% reduction)
Of games White won:
    Incorrect uct resigns = 115/118 (97.46%)
    Correct uct resigns = 3/118 (2.54%)
    No Resign = 0/118 (0.00%)
    Average game length = 453. Average game length with resigns = 2 (99.55% reduction)
Of all games:
    Incorrect uct resigns = 118/216 (54.63%)
    Correct uct resigns = 98/216 (45.37%)
    No Resign = 0/216 (0.00%)
    Average game length = 452. Average game length with resigns = 2 (99.54% reduction)

Resign rate: 0.20
Black won 98/216 (45.37%)
Of games Black won:
    Incorrect uct resigns = 17/98 (17.35%)
    Correct uct resigns = 81/98 (82.65%)
    No Resign = 0/98 (0.00%)
    Average game length = 451. Average game length with resigns = 113 (74.88% reduction)
Of games White won:
    Incorrect uct resigns = 31/118 (26.27%)
    Correct uct resigns = 86/118 (72.88%)
    No Resign = 1/118 (0.85%)
    Average game length = 453. Average game length with resigns = 115 (74.63% reduction)
Of all games:
    Incorrect uct resigns = 48/216 (22.22%)
    Correct uct resigns = 167/216 (77.31%)
    No Resign = 1/216 (0.46%)
    Average game length = 452. Average game length with resigns = 114 (74.74% reduction)

Resign rate: 0.15
Black won 98/216 (45.37%)
Of games Black won:
    Incorrect uct resigns = 14/98 (14.29%)
    Correct uct resigns = 84/98 (85.71%)
    No Resign = 0/98 (0.00%)
    Average game length = 451. Average game length with resigns = 134 (70.21% reduction)
Of games White won:
    Incorrect uct resigns = 28/118 (23.73%)
    Correct uct resigns = 89/118 (75.42%)
    No Resign = 1/118 (0.85%)
    Average game length = 453. Average game length with resigns = 140 (69.07% reduction)
Of all games:
    Incorrect uct resigns = 42/216 (19.44%)
    Correct uct resigns = 173/216 (80.09%)
    No Resign = 1/216 (0.46%)
    Average game length = 452. Average game length with resigns = 137 (69.59% reduction)

Resign rate: 0.10
Black won 98/216 (45.37%)
Of games Black won:
    Incorrect uct resigns = 11/98 (11.22%)
    Correct uct resigns = 87/98 (88.78%)
    No Resign = 0/98 (0.00%)
    Average game length = 451. Average game length with resigns = 151 (66.42% reduction)
Of games White won:
    Incorrect uct resigns = 17/118 (14.41%)
    Correct uct resigns = 100/118 (84.75%)
    No Resign = 1/118 (0.85%)
    Average game length = 453. Average game length with resigns = 162 (64.20% reduction)
Of all games:
    Incorrect uct resigns = 28/216 (12.96%)
    Correct uct resigns = 187/216 (86.57%)
    No Resign = 1/216 (0.46%)
    Average game length = 452. Average game length with resigns = 157 (65.21% reduction)

Resign rate: 0.05
Black won 98/216 (45.37%)
Of games Black won:
    Incorrect uct resigns = 10/98 (10.20%)
    Correct uct resigns = 88/98 (89.80%)
    No Resign = 0/98 (0.00%)
    Average game length = 451. Average game length with resigns = 170 (62.12% reduction)
Of games White won:
    Incorrect uct resigns = 10/118 (8.47%)
    Correct uct resigns = 105/118 (88.98%)
    No Resign = 3/118 (2.54%)
    Average game length = 453. Average game length with resigns = 182 (59.69% reduction)
Of all games:
    Incorrect uct resigns = 20/216 (9.26%)
    Correct uct resigns = 193/216 (89.35%)
    No Resign = 3/216 (1.39%)
    Average game length = 452. Average game length with resigns = 177 (60.79% reduction)

Resign rate: 0.02
Black won 98/216 (45.37%)
Of games Black won:
    Incorrect uct resigns = 7/98 (7.14%)
    Correct uct resigns = 90/98 (91.84%)
    No Resign = 1/98 (1.02%)
    Average game length = 451. Average game length with resigns = 193 (57.20% reduction)
Of games White won:
    Incorrect uct resigns = 8/118 (6.78%)
    Correct uct resigns = 107/118 (90.68%)
    No Resign = 3/118 (2.54%)
    Average game length = 453. Average game length with resigns = 198 (56.15% reduction)
Of all games:
    Incorrect uct resigns = 15/216 (6.94%)
    Correct uct resigns = 197/216 (91.20%)
    No Resign = 4/216 (1.85%)
    Average game length = 452. Average game length with resigns = 196 (56.62% reduction)

Resign rate: 0.01
Black won 98/216 (45.37%)
Of games Black won:
    Incorrect uct resigns = 5/98 (5.10%)
    Correct uct resigns = 91/98 (92.86%)
    No Resign = 2/98 (2.04%)
    Average game length = 451. Average game length with resigns = 201 (55.43% reduction)
Of games White won:
    Incorrect uct resigns = 8/118 (6.78%)
    Correct uct resigns = 107/118 (90.68%)
    No Resign = 3/118 (2.54%)
    Average game length = 453. Average game length with resigns = 204 (54.85% reduction)
Of all games:
    Incorrect uct resigns = 13/216 (6.02%)
    Correct uct resigns = 198/216 (91.67%)
    No Resign = 5/216 (2.31%)
    Average game length = 452. Average game length with resigns = 203 (55.11% reduction)
`

**Comment by killerducky** [comment]
@gcp I saw you mentioned adding data to the training files to support resign analysis on the server. But what about calculating `black_min_eval` and `white_min_eval`, and have autogtp upload those as metadata? It might be easier than changing the training the file format, and we could do it during this run making sure it all works. I can work on this if you think it's a good idea.

**Comment by dzhurak** [comment]
One of the latest validation game http://zero.sjeng.org/viewmatch/73137bf013e8b0a3eafd61af5c105e784d7c5eb6d877fdcdf6a8f9d8aa8b6d86?viewer=wgo
I'd say it resigned too early. White is clearly in the lead but still too early for black to resign.

**Comment by billyswong** [comment]
What's the current false resign rate in the self-play games? @dzhurak your concern cannot be handled unless somebody (e.g. @roy7) confirmed that data.

**Comment by billyswong** [comment]
Any update of current false resign rate @gcp ? Just saw one self-play games in my computer that would have false resigned if not for `-r 0`. Most games are played in `-r 10` but we as clients have no obvious ways to assess how that translate to actual false resign rate.
http://zero.sjeng.org/view/0e043fd37e31ebced17ab3e3d1738e12c7d7363c0bb95e76c21cd5c7f2dcbb3b?viewer=wgo

**Comment by MaxMaki** [comment]
@billyswong @dzhurak please see this thread: 
https://github.com/gcp/leela-zero/issues/971

Resigns were set to 10% after it was shown that this will result in less than 5% of incorrect resigns. So the same as AlphaGoZero used.

WhiteHalmos found in his analysis that the incorrect resign rate is 3%. This wasn't long ago, and the trend has been downwards on the amount of errors in resign.

You as a client have all the tools you need to do this analysis yourself as well. Save your AutoGTP games (not sure if you need debug as well, but autogtp ---help will give you the flags needed)
You can then run the resign analysis script found with the LeelaZero installation yourself.

So if you think the resign is too high, play a few hundred games and analyse it, but the data for now is pointing towards 10% being correct, and possibly even 15%.

**Comment by alreadydone** [comment]
` (netwinrate, root_uctwinrate, child_uctwinrate, bestmovevisits) = fh.readline().split()`
Found this line in scripts/resign_analysis/resign_analysis.py
Now I know what the numbers in the debug files mean ... Yes you need `autogtp -d <directory>` to save data for resign analysis ...

**Comment by Ishinoshita** [comment]
Can someone briefly explain how, at training server side, are -r 0 self-play games used to monitor the false positive rate and consequently the validity of the resign threshold ?
In almost all issues I found related to resign threshold analysis, it seems to me that some of you generated a bunch if -r 0 self-play games with debug enabled, then used the python script to produce stats. I haven't been able to spot stats based on the whole training data.
Last question: what is the target percentage of -r 0 self-play games pushed to contributor PC ? I thought it was 10% but I noticed it's more in the range of 12%-15% (based on analysing a slice of the last 400 games on sjeng.org from time to time).

**Comment by Hersmunch** [comment]
> Can someone briefly explain how, at training server side, are -r 0 self-play games used to monitor the false positive rate and consequently the validity of the resign threshold ?

As far as I know, it isn't. I think it would be of interest though https://github.com/gcp/leela-zero-server/issues/33.

> Last question: what is the target percentage of -r 0 self-play games pushed to contributor PC ?
I haven't looked myself but @Nazgand commented recently that it is 20% https://github.com/gcp/leela-zero/pull/1581#discussion_r200828323

As I understand, no resign games are useful for two things; analysis of the wrong resign rate & resign threshold as well as to provide extra data to learn endgame from (as it will be missing from many resign enabled games).
